import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fungi World',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
    <link rel="icon" href="/images/favicon.png" sizes="any" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}